const ADD_STUDENT = "ADD_STUDENT";
const DELETE_STUDENT = "DELETE_STUDENT";
const EDIT_STUDENT = "EDIT_STUDENT";
const UPDATE_STUDENT = "UPDATE_STUDENT";

export { ADD_STUDENT, DELETE_STUDENT, EDIT_STUDENT, UPDATE_STUDENT };
